all: wendys mainArray mainLinked

Wendys: Wendys.cpp Customer.h Customer.cpp Cashier.h Cashier.cpp
	g++ -o wendys Wendys.cpp Customer.cpp Cashier.cpp

mainArray: queueA.h Array.cpp queueA.cpp
	g++ -o mainArray mainArray.cpp

mainLinked: queueL.h Link.cpp queueL.cpp
	g++ -o mainLinked mainLink.cpp


